//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LtopDesctopAPI.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertVersion
    {
        public long ID { get; set; }
        public Nullable<long> AdvertId { get; set; }
        public Nullable<long> VersionNumber { get; set; }
        public string Value { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Advert Advert { get; set; }
    }
}
