//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LtopDesctopAPI.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.AdvertsToDevices = new HashSet<AdvertsToDevice>();
            this.SeriesToDevices = new HashSet<SeriesToDevice>();
            this.DevicesToPhotoes = new HashSet<DevicesToPhoto>();
            this.PropertyToDevices = new HashSet<PropertyToDevice>();
        }
    
        public long ID { get; set; }
        public Nullable<long> VendorsId { get; set; }
        public Nullable<long> ModelsId { get; set; }
        public Nullable<int> DeviceCategoryId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string DescriptionEng { get; set; }
        public string DescriptionRus { get; set; }
        public string DescriptionUkr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvertsToDevice> AdvertsToDevices { get; set; }
        public virtual DeviceCategory DeviceCategory { get; set; }
        public virtual Model Model { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeriesToDevice> SeriesToDevices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevicesToPhoto> DevicesToPhotoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyToDevice> PropertyToDevices { get; set; }
    }
}
