//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LtopDesctopAPI.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorsToDeviceCategory
    {
        public long ID { get; set; }
        public Nullable<long> VendorsId { get; set; }
        public Nullable<int> DevicesCategoryId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual DeviceCategory DeviceCategory { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
